const seedUsers = [
  {
    name: 'Alice Admin',
    email: 'admin@teamup.dev',
    password: 'password123',
    role: 'ADMIN',
  },
  {
    name: 'Bob Manager',
    email: 'manager@teamup.dev',
    password: 'password123',
    role: 'MANAGER',
  },
  {
    name: 'Charlie Member',
    email: 'charlie@teamup.dev',
    password: 'password123',
    role: 'MEMBER',
  },
  {
    name: 'Diana Member',
    email: 'diana@teamup.dev',
    password: 'password123',
    role: 'MEMBER',
  },
  {
    name: 'Evan Member',
    email: 'evan@teamup.dev',
    password: 'password123',
    role: 'MEMBER',
  },
];

const seedProjects = [
  {
    name: 'Home Renovation & Living Room Makeover',
    description: 'Redecorating and renovating the living room with fresh paint, cozy modular sofa, new warm lighting, and hardwood flooring.',
  },
  {
    name: 'Sweet Delights Bakery & Cafe Launch',
    description: 'Opening a neighborhood artisan bakery, perfecting dessert recipes, setting up online cake ordering, and hosting grand opening.',
  },
  {
    name: 'Summer Family Vacation & Coastal Road Trip',
    description: 'Planning an unforgettable 7-day coastal road trip with the family including beach cottages, scenic hiking, and campfire dinners.',
  },
  {
    name: 'Community 5K Charity Fun Run',
    description: 'Organizing an annual charity run and festival in the city park to raise funds for the local children’s animal shelter.',
  },
];

const getSeedTasks = (proj1Id, proj2Id, proj3Id, proj4Id, userMap) => [
  // --- Project 1: Home Renovation ---
  {
    title: 'Pick wall paint colors & order wallpaper samples',
    description: 'Visit the paint store, select warm neutral palettes (beige, soft sage), and test swatches on the accent wall.',
    project: proj1Id,
    assignedTo: userMap['charlie@teamup.dev'],
    createdBy: userMap['manager@teamup.dev'],
    status: 'DONE',
    priority: 'HIGH',
    dueDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    version: 1,
  },
  {
    title: 'Order hardwood flooring & tile adhesive',
    description: 'Calculate square footage for 450 sq ft living room and order moisture-resistant oak planks.',
    project: proj1Id,
    assignedTo: userMap['diana@teamup.dev'],
    createdBy: userMap['manager@teamup.dev'],
    status: 'DONE',
    priority: 'MEDIUM',
    dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    version: 1,
  },
  {
    title: 'Install ceiling fan & warm dimmable pendant lights',
    description: 'Hire certified electrician to install modern black pendant fixtures and replace old light switches with smart dimmers.',
    project: proj1Id,
    assignedTo: userMap['charlie@teamup.dev'],
    createdBy: userMap['manager@teamup.dev'],
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    version: 1,
  },
  {
    title: 'Assemble 3-seater modular sofa & coffee table',
    description: 'Unbox furniture shipment, tighten legs, arrange sectional cushions, and apply fabric stain protector.',
    project: proj1Id,
    assignedTo: userMap['evan@teamup.dev'],
    createdBy: userMap['manager@teamup.dev'],
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    dueDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    version: 1,
  },
  {
    title: 'Mount 65-inch Smart TV and conceal wires',
    description: 'Fix heavy-duty wall bracket into studs, level TV, and run cable conduits behind drywall.',
    project: proj1Id,
    assignedTo: userMap['admin@teamup.dev'],
    createdBy: userMap['manager@teamup.dev'],
    status: 'TODO',
    priority: 'HIGH',
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    version: 1,
  },
  {
    title: 'Schedule deep carpet cleaning before move-in',
    description: 'Book professional steam cleaning service for Saturday morning before final furniture layout.',
    project: proj1Id,
    assignedTo: userMap['diana@teamup.dev'],
    createdBy: userMap['manager@teamup.dev'],
    status: 'TODO',
    priority: 'LOW',
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    version: 1,
  },

  // --- Project 2: Sweet Delights Bakery ---
  {
    title: 'Finalize dessert menu & price list',
    description: 'Select signature items: chocolate croissants, sourdough loaves, strawberry tarts, and matcha lattes.',
    project: proj2Id,
    assignedTo: userMap['manager@teamup.dev'],
    createdBy: userMap['admin@teamup.dev'],
    status: 'DONE',
    priority: 'HIGH',
    dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    version: 1,
  },
  {
    title: 'Professional food photography for cakes & pastries',
    description: 'Capture mouth-watering hero photos with natural studio lighting for our online menu and social media.',
    project: proj2Id,
    assignedTo: userMap['diana@teamup.dev'],
    createdBy: userMap['manager@teamup.dev'],
    status: 'DONE',
    priority: 'MEDIUM',
    dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    version: 1,
  },
  {
    title: 'Set up online cake ordering & payment gateway',
    description: 'Enable customers to pre-order custom birthday cakes, choose pickup times, and pay securely via card or Apple Pay.',
    project: proj2Id,
    assignedTo: userMap['charlie@teamup.dev'],
    createdBy: userMap['manager@teamup.dev'],
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    version: 1,
  },
  {
    title: 'Order branded takeaway boxes & eco coffee cups',
    description: 'Order 1,000 biodegradable pastry boxes and insulated coffee cups with bakery logo embossed.',
    project: proj2Id,
    assignedTo: userMap['evan@teamup.dev'],
    createdBy: userMap['manager@teamup.dev'],
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    version: 1,
  },
  {
    title: 'Host weekend grand opening free tasting event',
    description: 'Offer free miniature cinnamon rolls and iced coffee samples between 10 AM and 2 PM to neighborhood residents.',
    project: proj2Id,
    assignedTo: userMap['manager@teamup.dev'],
    createdBy: userMap['admin@teamup.dev'],
    status: 'TODO',
    priority: 'HIGH',
    dueDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000),
    version: 1,
  },

  // --- Project 3: Summer Family Vacation ---
  {
    title: 'Book pet-friendly beachfront cottage',
    description: 'Confirmed reservation for 4-bedroom oceanfront cottage with enclosed backyard and grill.',
    project: proj3Id,
    assignedTo: userMap['manager@teamup.dev'],
    createdBy: userMap['manager@teamup.dev'],
    status: 'DONE',
    priority: 'HIGH',
    dueDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    version: 1,
  },
  {
    title: 'Car maintenance check (oil, tires, brakes)',
    description: 'Take minivan to certified auto center for 50-point inspection and fluid top-up before 800-mile trip.',
    project: proj3Id,
    assignedTo: userMap['charlie@teamup.dev'],
    createdBy: userMap['manager@teamup.dev'],
    status: 'DONE',
    priority: 'HIGH',
    dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    version: 1,
  },
  {
    title: 'Plan daily sightseeing spots & hiking trails',
    description: 'Map scenic cliff walk on Day 2, lighthouse tour on Day 4, and sunset kayak rental on Day 6.',
    project: proj3Id,
    assignedTo: userMap['diana@teamup.dev'],
    createdBy: userMap['manager@teamup.dev'],
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    version: 1,
  },
  {
    title: 'Buy sunscreen, beach umbrellas & camping chairs',
    description: 'Pick up SPF 50 mineral sunscreen, 2 lightweight portable beach umbrellas, and portable cooler.',
    project: proj3Id,
    assignedTo: userMap['evan@teamup.dev'],
    createdBy: userMap['manager@teamup.dev'],
    status: 'TODO',
    priority: 'LOW',
    dueDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    version: 1,
  },
  {
    title: 'Prepare road trip playlist and travel snacks',
    description: 'Curate 6-hour family music playlist and pack homemade trail mix, fruit snacks, and water bottles.',
    project: proj3Id,
    assignedTo: userMap['charlie@teamup.dev'],
    createdBy: userMap['manager@teamup.dev'],
    status: 'TODO',
    priority: 'LOW',
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    version: 1,
  },

  // --- Project 4: Community 5K Charity Run ---
  {
    title: 'Secure city park permit & mark 5K running route',
    description: 'Permit approved by Parks Department. Route mapped along the lakeside trail with start/finish arch.',
    project: proj4Id,
    assignedTo: userMap['admin@teamup.dev'],
    createdBy: userMap['admin@teamup.dev'],
    status: 'DONE',
    priority: 'HIGH',
    dueDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    version: 1,
  },
  {
    title: 'Design & order runner t-shirts and medals',
    description: 'Order 300 breathable dri-fit shirts and custom engraved animal rescue finisher medals.',
    project: proj4Id,
    assignedTo: userMap['diana@teamup.dev'],
    createdBy: userMap['admin@teamup.dev'],
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    version: 1,
  },
  {
    title: 'Recruit volunteer team for hydration water stations',
    description: 'Assign 8 volunteers to 1-mile, 2-mile, and finish line hydration stations with paper cups and water coolers.',
    project: proj4Id,
    assignedTo: userMap['charlie@teamup.dev'],
    createdBy: userMap['admin@teamup.dev'],
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    dueDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    version: 1,
  },
  {
    title: 'Rent timing mats, digital race clock & sound system',
    description: 'Coordinate with local athletics timing company for chip timing mats and loud PA speaker system.',
    project: proj4Id,
    assignedTo: userMap['manager@teamup.dev'],
    createdBy: userMap['admin@teamup.dev'],
    status: 'TODO',
    priority: 'HIGH',
    dueDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000),
    version: 1,
  },
  {
    title: 'Coordinate with local food trucks & smoothie vendors',
    description: 'Confirm 3 food trucks for post-race celebration: fresh fruit smoothies, breakfast burritos, and specialty coffee.',
    project: proj4Id,
    assignedTo: userMap['evan@teamup.dev'],
    createdBy: userMap['admin@teamup.dev'],
    status: 'TODO',
    priority: 'LOW',
    dueDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000),
    version: 1,
  },
];

module.exports = {
  seedUsers,
  seedProjects,
  getSeedTasks,
};
